version: '3.8'

services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/var/www/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - defaultNetwork
  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST:db
      - POSTGRES_USER=anaresgalla
      - POSTGRES_PASSWORD=marketplace
      - POSTGRES_DB=marketplace_api_development
    networks:
      - defaultNetwork
    
networks:
  defaultNetwork:
    driver: bridge

volumes:
  postgres_data:
