default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: marketplace_api_development
  host:  db # localhost (tem mudar qdo Docker)
  port: 5432
  username: anaresgalla
  password: marketplace

test:
  <<: *default
  database: marketplace_api_test
  host: db # localhost (tem mudar qdo Docker)
  port: 5432
  username: anaresgalla
  password: marketplace

production:
  <<: *default
  database: marketplace_api_production
  username: 'anaresgalla'
  password: 'marketplace'
